services:
  # Single Flask backend serving both API and frontend
  - type: web
    name: chatwithpdf-app
    env: docker
    dockerfilePath: ./Dockerfile.flask
    plan: free
    envVars:
      - key: PORT
        sync: false
      - key: FLASK_ENV
        value: "production"
    disk:
      name: app-data
      mountPath: /app/data
      sizeGB: 1
