services:
  # Backend service
  - type: web
    name: chatwithpdf-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: starter
    region: oregon
    envVars:
      - key: PORT
        value: 8000
    disk:
      name: chroma-data
      mountPath: /app/chroma_db
      sizeGB: 1
    
  # Frontend service  
  - type: web
    name: chatwithpdf-frontend
    env: docker
    dockerfilePath: frontend/Dockerfile
    dockerContext: frontend
    plan: starter
    region: oregon
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://chatwithpdf-backend.onrender.com/api/v1
