services:
  # Backend service using simple approach
  - type: web
    name: chatwithpdf-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: starter
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
    disk:
      name: chroma-data
      mountPath: /app/chroma_db
      sizeGB: 1
  
  # Frontend service  
  - type: web
    name: chatwithpdf-frontend
    env: docker
    dockerfilePath: frontend/Dockerfile
    dockerContext: frontend
    plan: starter
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://chatwithpdf-backend.onrender.com/api/v1
