services:
  # Single service deployment using simple Docker approach
  - type: web
    name: chatwithpdf-app
    env: docker
    dockerfilePath: Dockerfile.simple
    dockerContext: .
    plan: starter
    envVars:
      - key: PORT
        value: 8000
    disk:
      name: chroma-data
      mountPath: /app/chroma_db
      sizeGB: 1
